name: 'CI'

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    branches:
      - develop
      - release/*

jobs:
  test-cypress:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      # - name: set env
      #   run: cp .env.test .env.local
      - uses: cypress-io/github-action@v6
        with:
          build: npm run export
          start: npm run serve

  ts-prune:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ts-prune
        shell: bash
        run:
          ts-prune --ignore "/*.stories.tsx | src/pages/*" |
            grep -v -E "src/(app|pages)/.* - (default|GET|dynamic)" |
            grep -v getServerSideProps |
            (! grep -v -E "(ts-prune --ignore|Done in |npm run)")